### ISSUE TITLE
Preventing empty strings from being sent to Solr unnecessary?

### ISSUE THREAD

**Issue by llvtt** [django-haystack/pysolr#150]
[`_is_null_value`](https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L579-L586) prevents fields that map to the empty string from being sent to Solr. Why is that? The [comment](https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L588) around this code suggests that this averts some issue within Solr itself, but Solr 4.10 at least seems to be able to handle this. Should pysolr continue to filter out empty string values?

**Comment by acdha** [comment]
Hmmm, yes, this could at the very least have better documentation – preferably at least a pointer to a bug tracker or something.

A quick search turns up this original commit:

https://github.com/toastdriven/pysolr/commit/f35f968ec2b1aa3e2b70bd4572ecedf7eb53f36d

… with the bug here:

https://code.google.com/p/pysolr/issues/detail?id=22

and what appears to be the referenced SVN commit:

http://svn.apache.org/viewvc?view=revision&revision=796334

**Comment by peter721** [comment]
I'm assuming this fix was written to solve a bug in a much older version of Solr - the current version was 1.3 at the time of this commit. Is there known support for certain versions of Solr? I see on the landing page that a link to Solr 4 is provided - does the code assume version 4?

**Comment by domenkozar** [comment]
I think this raises a question what Solr versions should pysolr officially support.

**Comment by atuljangra** [comment]
This bug is still there?

**Comment by acdha** [comment]
@atuljangra It doesn't seem like there's a whole lot of interest in this. If you want to send a pull request with working tests it looks like something we could merge easily.

**Comment by atuljangra** [comment]
@acdha I'll see what I can do. I'll ping here for details if I can find time to do this.

**Comment by atuljangra** [comment]
@acdha  I did change the pysolr to reflect adding the null string. But this problem is with Lucene. I'm using the current solr and if I send an empty field, even then Lucene won't detect it and the field is absent.
I am at Solr 5.4.1 and I've tried adding using pysolr and by curling too.
`curl http://localhost:8983/solr/new_core/update -d '
[
 {"id" : "book1",
  "title" : "The Way of Kings", "rssurl":""
 }
]'
{"responseHeader":{"status":0,"QTime":3}}`

And also, the following xml is being sent using pysolr
`<add><doc><field name="id">doc_1</field><field name="title">A test document</field></doc><doc><field name="id">doc_2</field><field name="title">The Banana: Tasty or Dangerous?</field></doc><doc><field name="rssurl" /><field name="id">doc_4</field><field name="title" /></doc></add>`

I guess leaving this is the only option.

**Comment by acdha** [comment]
Okay, so I guess we should just close this issue until we have reason to be believe this is fixed upstream and widely deployed?

Perhaps it would make sense to add a link to this issue in a comment for the next time someone wonders why this happened since it's definitely not clear currently.

**Comment by elitzer2** [comment]
I ended up using requests to formulate my own query because PySolr doesn't send an empty string to a text field in order to clear it out. Are there future plans to support this?
