### ISSUE TITLE
How can I use 'facet.query=price:[1000+TO+2000]'?

### ISSUE THREAD

**Issue by chengbo** [django-haystack/pysolr#158]
`facet.query=price:[1000+TO+2000]`
will be encoded to
`facet.query=price%3A%5B1000%2BTO%2B2000%5D`

then Solr will response HTTP 400 error with below message

`"org.apache.solr.search.SyntaxError: Cannot parse 'price:[1000+TO+2000]': Encountered \" \"]\" \"] \"\" at line 1, column 19.\nWas expecting one of:\n    \"TO\" ...\n    <RANGE_QUOTED> ...\n    <RANGE_GOOP> ...\n    "`

How can I prevent pysolr to encode these characters?
pysolr: 3.2.0  
Solr: 5.1

**Comment by swistakm** [comment]
**tr;dr:** use spaces

@chengbo the error message tells you exactly what wrong is with your query. Formatted:
```
org.apache.solr.search.SyntaxError: Cannot parse 'price:[1000+TO+2000]': Encountered " "]" "] "" at line 1, column 19.
Was expecting one of:
 "TO" ...
 <RANGE_QUOTED> ...
 <RANGE_GOOP> ...
```

It encountered `]` character on the end where it was expecting `'TO'`,  `<RANGE_QUOTED>` `<RANGE_GOOP>`. If you read carefully Solr documentation you'll find that `<RANGE_QUOTED>` decimal 31 ASCII character (Unit separator) and `<RANGE_GOOP>` is decimal 32 ASCII char (Space). This means that substring `1000+TO+2000` was parsed as the first value of range query in following form: `[<first_value><separator>TO<separator><second_value>]' and could not find the rest.

Use spaces as a separator instead of '+' character.

self-advertisement: using [solrq](https://github.com/swistakm/solrq) would save you from such problems:

    from solrq import Range, Q
    solr.search('*:*', facet='true', **{'facet.query': Q(price=Range(1000, 2000))})
