### ISSUE TITLE
CSV Output

### ISSUE THREAD

**Issue by haveaguess** [django-haystack/pysolr#179]
_select is hardcoded to return json 

would be nice to get some csv support for our use cases

**Comment by acdha** [comment]
If you wanted to contribute a pull request, the core part would be fairly simple – mostly changing the areas where [it sets `wt = json`](https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L402) to only do so when the provided parameters doesn't include `wt`. 

The harder part would be deciding what to do for the higher-level interfaces where e.g. https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L704-L711 expects to get a dict-like object out. I think that might be best tackled by creating a CSV response class and modifying the logging calls to do something like using the `.hits` / `.docs` properties on `pysolr.Results` rather than trying to pull values out of the response directly:

https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L272-L273

If this is useful to you, please send a pull request & I'll review it.

**Comment by swistakm** [comment]
It seems like a very good idea (`wt` as a class atribute of `response_cls`). This way it is possible to easlily provide support for other formats in the client code. There is not a lot of reasonable choices of alternative right now but may be handy if someone wants to provide his own Response Writer to Solr.

**Comment by haveaguess** [comment]
Thanks for reply

That makes a lot of sense, I'll see if we can find some bandwidth to contribute this 

It would be nice to us to use Pysolr throughout, but for our CSV download we are currently using our own legacy low level request url (with our own GET/POST type switching etc) 

I'll leave it open for now, if you want to close I'll understand though

Regards
Ben

**Comment by acdha** [comment]
I think @swistakm is on to the reason for keeping this open – it'd be nice to make it easier to implement custom result classes which are different from the current JSON behaviour and it looks like this could be fairly simple except for the logging calls, which are due for some cleanup.

**Comment by vvolkman** [comment]
I'd like to allow wt=xml to return the unpreturbed SOLR xml format
