### ISSUE TITLE
Error: Unknown collection - SolrCloud __init__

### ISSUE THREAD

**Issue by pdelboca** [django-haystack/pysolr#189]
Hi!
I'm having an error when trying to create a new SolrCloud object.

```
File "/home/patodb/Repos/hdfs_solr_indexer/indexer.py", line 23, in __init__
    self.solr = SolrCloud(zk, collection)
File "/home/patodb/Repos/hdfs_solr_indexer/pysolr.py", line 1148, in __init__
    url = zookeeper.getRandomURL(collection)
File "/home/patodb/Repos/hdfs_solr_indexer/pysolr.py", line 1289, in getRandomURL
    return random.choice(self.getHosts(collname, only_leader=False)) + "/" + collname
File "/home/patodb/Repos/hdfs_solr_indexer/pysolr.py", line 1255, in getHosts
    raise SolrError("Unknown collection: %s", collname)
pysolr.SolrError: (u'Unknown collection: %s', 'boletines_cba')
```

The error is raised in the `getHosts` method of the `ZooKeeper` class. Debugging the program I found that `self.collections` and `self.aliases` are not being initialized correctly when creating the ZooKeeper object. **Both variables have the default value {}** at the time `getRandomURL()` is executed and I don't see a workflow where these values are overriden.

The Zookeeper object (from Kazoo) seems fine, it resolves both the urls and chroot correctly. The server is running and the collection exists. Any ideas about why is this happening?

Regards,

**Comment by Liu-Feng** [comment]
I have same problem with solr5.5,Current code reads "/clusterstate.json" on zookeeper,try change ZooKeeper.CLUSTER_STATE to "/collections/<your collection>/state.json",it works for me.

**Comment by acdha** [comment]
There's an open pull request in progress: https://github.com/django-haystack/pysolr/pull/187

**Comment by aodavid** [comment]
I have same problem with solr6,  it will be fixed later?

**Comment by willderivera** [comment]
Are there plans to release the fix in #187 ? Solr is currently at version 6 while the pull request says it supports 5 and master only supports 4. Most of this library is great when dealing with a single instance of Solr, but it is unusable with Solr in cloud mode. I tried running #187 and it did work, but it's 45 commits and two minor versions behind master and I don't want to miss out on those changes. This is the only Python Solr client I could find that is aware of Zookeeper so I would much rather use it than one of the other options

**Comment by Qinwenchao** [comment]
i have solved the problem.
due to the solr /clusterstate.json has been replaced by  /collections/%s/state.json

1) consts
@@ -1242,6 +1242,8 @@ class ZooKeeper(object):
+    COLLECTION_STATUS = '/collections'
+    CLUSTER_DETAIL_STATE = '/collections/%s/state.json'

2) two new function   
    a) watchClusterDetailState
    b) watchClusterState
+        def watchClusterDetailState(data, *args, **kwargs):
+            if not data:
+                LOG.warning("No cluster state available: no collections defined?")
+            else:
+                self.collections.update(json.loads(data.decode('utf-8')))
+                LOG.info('Updated collections: %s', self.collections)
+
+        @self.zk.ChildrenWatch(ZooKeeper.COLLECTION_STATUS)
+        def watchClusterState(children):
+            LOG.info("Updated collection: %s", children)
+            for c in children:
+                self.zk.DataWatch(self.CLUSTER_DETAIL_STATE % c, watchClusterDetailState)

3) to be compatible with old version
                 def watchClusterState(data, *args, **kwargs):
-                self.collections = json.loads(data.decode('utf-8'))
+                self.collections.update(json.loads(data.decode('utf-8')))


I want to commit my code to fix it . How? i can not launch a merge request.

**Comment by jdossett** [comment]
@Qinwenchao 

1. Fork the pysolr repository
2. Clone your fork to your local machine
3. Commit your changes to your master.
4. Push to your github fork.
5. Open a PR from your repo to this repo.
