### ISSUE TITLE
How pysolr handle with Multivalued fields?

### ISSUE THREAD

**Issue by RominYue** [django-haystack/pysolr#196]
code snippet below is ok?
```python
solr.add([
    {
        "id": "doc_1",
        "title": "A test document",
        "link": "baidu.com",
        "link": "google.com"
    },
])
```

when return results have multi-valued field, How we handle this?

**Comment by acdha** [comment]
The issue tracker is for reporting problems, not a general QA forum. I would suggest somewhere like StackOverflow.com for that in general.

In this case, the example above is technically valid Python but the results aren't what you expect since a dictionary can only have one value for a given key:

```
>>> {'foo': 'bar', 'foo': 'baz'}
{'foo': 'baz'}
>>> 
```

In pysolr we handle this by using lists for multi-valued fields: 

```
solr.add([
    {
        "id": "doc_1",
        "title": "A test document",
        "link": ["baidu.com", "google.com"]
    },
])
```
