### ISSUE TITLE
How to load large amount of documents? (add results in ConnectionError when loading 5K documents)

### ISSUE THREAD

**Issue by Paul424** [django-haystack/pysolr#231]
I have many small documents (with 13 fields, doc size is +/- 0.5KB) and i like to batch load these to reduce the number of API calls and to improve the performance.

We noticed that we somehow cannot scale-up to the amounts we like, sending chunks of 1K documents work ok, but sending 5K documents already gives requests errors which we do not understand.

  File ".../pysolr.py", line 376, in _send_request
    timeout=self.timeout, auth=self.auth)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

We are running:
requests 2.18.4
pysolr 3.7.0

**Comment by swistakm** [comment]
I bet this is more about tuning your solr instance/cluster or its usage rather than about the internals of pysolr.

Do you have access to Solr logs? I've seen such problems multiple times and usually Solr logs were very helpful.

You can also share some more information about the context of this error:
* How many such requests per second do you make?
* What is the error ratio? Does this error happen on every write request or only sometimes?
* Does these requests hav  `commit=True` set?
* Do you use any uncommon Solr features like external file fields?
* How is your autocommit configured in Solr?

**Comment by vvolkman** [comment]
You might also try submitting a smaller number of docs (1,000) per POST request but using 16+ threads.  That’s how we get high volume.
Then again your SOLR backend must be beefy enough to take the traffic.

**Comment by acdha** [comment]
@swistakm covered the main question I had: commit settings (hard/soft, interval) can make a big difference for how many updates your server can handle. What you need to pick is going to depend on your workload and the nature of your data — e.g. if you can easily recover from data loss if the server crashes after receiving an update but before committing it, you can be more aggressive in your tuning than someone who cannot.

This might be somewhat helpful:

https://lucidworks.com/2013/08/23/understanding-transaction-logs-softcommit-and-commit-in-sorlcloud/

**Comment by Paul424** [comment]
Some more info:
- We are sending the output from a spark job to solr; we do that from the executors so we are actually sending from (in this case) 20 executors. One optimization is that we send to all the endpoints (randomized), we not one node gets all the traffic.
- We send the events in a chunked fashion all commit=False and after that there is one solr.commit() done.
- When i noticed the requests were failing i took the failing data into a small local Python test application that reproduces this same issue. When i send the data (25K events) chunked in 1K sets then there is no issue, however when i send 5K events in each call I get this error (always). So there does not seem to be an issue with the data or schema.

I will run some more tests and taak a look at the server logs...

Paul

**Comment by swistakm** [comment]
@Paul424: Oh, I've misread the issue. I thought that you meant 5KB of request size and not 5000 documents. If your documents are ~0.5KB the estimated request body size will be ~2,5MB for 5000 of them. If you are running Solr version with built in jetty server (anything beyond 3.x I guess) then probably you've might just hit the size limit for POST requests that is by default 2MB in jetty. It can be configured with `org.eclipse.jetty.server.Request.maxFormContentSize` system property as documented [here](http://www.eclipse.org/jetty/documentation/9.4.8.v20171121/setting-form-size.html).

If this is the case it would be very easy to confirm it in Solr logs. Also it will make sense why your connection is simply closed by peer on the TCP level without normal HTTP response. If you don't have access to logs you may try to send arbitrary requests directly to Solr with increasing body size to see when it starts to drop connections. You don't even have to do it with legit JSON documents and can use curl for that because even if Solr cannot decode the requesr body it should at least respond with some 4xx status code (or 5xx if it cannot handle it's own decoding errors).

If you're using some old version of Solr sitting behind Tomcat it will have the similar configuration option available too.

**Comment by Paul424** [comment]
We are running solr 4.10.3, however when i test with curl sending random binary data i get Solr exceptions back up to 200MB (did not test beyond). Now i noticed pysolr sends in xml format so the document size will be larger than +/- 0.5KB but still i don't expect it's beyond 200MB.

What i have just also seen is that a test app first send chunks of 10K documents just fine (over and over and over again), but when i stress the system a bit more using a spark job it starts to fail quickly: ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer')). I'll try to reduce the worker count.

**Comment by efagerberg** [comment]
It would also be interesting to see what the resources look like on your system when they fail, you could be running out of heap or RAM.
