### ISSUE TITLE
Does pysolr support Solr 7.5?

### ISSUE THREAD

**Issue by tony-boxed** [django-haystack/pysolr#249]
I'm having an issue with solr-to-es because it's attempting to pull results from /solr/index/?q... but Solr 7.5 waits for /solr/index/select?q... so I'm getting 404 while attempting to transfer documents from Solr to Elasticsearch.

**Comment by acdha** [comment]
That sounds like a problem with the code calling pysolr. If you look at the implementation it takes a base URL and adds handlers such as `select` to it so it sounds like the `Solr` instance you're using  should be initiated with `/solr/index/` rather than `/solr/`:

https://github.com/django-haystack/pysolr/blob/master/pysolr.py#L297

**Comment by pu239ppy** [comment]
I am also having a similar issue, pysolr formats the path as handler/?q=search_string 
EX : `u'select/?q=state_s%3ANY&wt=json'`
What does work is when I fix that line of code to produce u'select?q=state_s%3ANY&wt=json'
this happens here https://github.com/django-haystack/pysolr/blob/bd53878b7c38f1e58f708a20bb73865613a462c6/pysolr.py#L436
