### ISSUE TITLE
Solr Authentication

### ISSUE THREAD

**Issue by mattparrilla** [django-haystack/pysolr#29]
First time submitting a feature request on github! Hopefully this is the right place...

My solr service comes with a username and password. It would be cool to be able to take advantage of it. I'd try and modify the source myself but I've only been programming for 6 months and haven't the slightest clue where I'd begin!

Thanks!

**Comment by philippeluickx** [comment]
+1

**Comment by philippeluickx** [comment]
Seems to work now, can someone confirm and close ticket?

**Comment by PaulIurea** [comment]
Is there a way to use Basic Authentication by not sending the username and password in clear in the connection URL? 

If one checks the logs after adding something to Solr, the URL with the connection credentials can be seen in clear. I know I could comment/remove the logging line from the source code, but that's not desirable.

**Comment by PaulIurea** [comment]
I think the quickest fix in case there is no other way to do it is to have that logged in debug mode rather than in info mode. This could be changed in pysolr.py line 382 from "self.log.info" to "self.log.debug". Maybe an admin could change this line for future releases.

**Comment by acdha** [comment]
@PaulIurea There's no way to avoid including it in the URL: HTTP Basic Authentication means cleartext. Changing the log level would make sense if you want to send a pull request. Looking at that chunk of code, I'm thinking that the best answer would be creating a little helper function which would sanitize the URL using urlparse to clear or mask the fields so we could retain the debugging value of the URLs without hoping that everyone sets their log levels appropriately, especially since in this case I think you'd also have to worry about the logging done by requests and urllib3.
